// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf4FeFYKY20n732oe8miFrvw7YA9XqBkI',
    appId: '1:582153316268:web:b4a97dd47b3caecdf43c09',
    messagingSenderId: '582153316268',
    projectId: 'alex-messenger',
    authDomain: 'alex-messenger.firebaseapp.com',
    storageBucket: 'alex-messenger.appspot.com',
    measurementId: 'G-NHQND28EQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvAlReqTjyNLmY9qDaII2fwoF5aidh2f4',
    appId: '1:582153316268:android:107a54622f069cf1f43c09',
    messagingSenderId: '582153316268',
    projectId: 'alex-messenger',
    storageBucket: 'alex-messenger.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYQps34bkj_TgFsmL4Z9pgtoJK-Vt85j0',
    appId: '1:582153316268:ios:2f33a0eb73428d30f43c09',
    messagingSenderId: '582153316268',
    projectId: 'alex-messenger',
    storageBucket: 'alex-messenger.appspot.com',
    iosClientId: '582153316268-0sv7ohgrjlo97fpsgtpni86cddcjmpnf.apps.googleusercontent.com',
    iosBundleId: 'com.alexcao.messenger.alexMessenger',
  );
}
